/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as PrototypesIndexRouteImport } from './routes/prototypes/index'
import { Route as PrototypesStepRouteImport } from './routes/prototypes/$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesIndexRoute = PrototypesIndexRouteImport.update({
  id: '/prototypes/',
  path: '/prototypes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesStepRoute = PrototypesStepRouteImport.update({
  id: '/prototypes/$step',
  path: '/prototypes/$step',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/prototypes/$step': typeof PrototypesStepRoute
  '/prototypes/': typeof PrototypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/prototypes/$step': typeof PrototypesStepRoute
  '/prototypes': typeof PrototypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRoute
  '/prototypes/$step': typeof PrototypesStepRoute
  '/prototypes/': typeof PrototypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor' | '/prototypes/$step' | '/prototypes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor' | '/prototypes/$step' | '/prototypes'
  id: '__root__' | '/' | '/editor' | '/prototypes/$step' | '/prototypes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRoute
  PrototypesStepRoute: typeof PrototypesStepRoute
  PrototypesIndexRoute: typeof PrototypesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/': {
      id: '/prototypes/'
      path: '/prototypes'
      fullPath: '/prototypes/'
      preLoaderRoute: typeof PrototypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/$step': {
      id: '/prototypes/$step'
      path: '/prototypes/$step'
      fullPath: '/prototypes/$step'
      preLoaderRoute: typeof PrototypesStepRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRoute,
  PrototypesStepRoute: PrototypesStepRoute,
  PrototypesIndexRoute: PrototypesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
